
services:

  dragonfly:
    # 明确指定稳定版，避免 latest 自动更新
    image: docker.dragonflydb.io/dragonflydb/dragonfly:${DRAGONFLY_VERSION}
    container_name: dragonfly-redis-${SERVICE_PORT}
    restart: always
    privileged: true

    network_mode: host  # mac os 会失效  ports:  去掉！！！
    #    ports:
    #      - "${SERVICE_PORT}:${SERVICE_PORT}"
    command:
      - --bind=127.0.0.1
      - --port=6379
      - --requirepass=bNBmfftDPvzJWU87
      - --dbfilename=dump
      - --dir=/data
      - --maxmemory=4G
    volumes:
      - ./dragonfly-data-${SERVICE_PORT}:/data
      - ./custom-hosts:/etc/hosts:ro  # 只读挂载
