
services:

  redis:
    # 明确指定稳定版，避免 latest 自动更新
    image: redis:${REDIS_VERSION}
    container_name: redis-${SERVICE_PORT}
    restart: always
    privileged: true

#    network_mode: host      #数据库和Redis网络模式尽量不用桥接模式，使用host模式, 以免损失性能; 但是在 mac os host模式会导致服务无法访问

    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"

    command:
#      - --bind 127.0.0.1
      - --port 6379
#      - --requirepas
      - --dir /data
      - --maxmemory 2G
      - --maxclients 50000
      # 多线程数量 = CPU核心数
      - --io-threads 2
      # 开启读多线程
      - --io-threads-do-reads yes
    volumes:
      - ./data-${SERVICE_PORT}:/data
      - ./custom-hosts:/etc/hosts:ro  # 只读挂载
