
services:

  redis:
    # 明确指定稳定版，避免 latest 自动更新
    image: redis:${REDIS_VERSION}
    container_name: redis-${SERVICE_PORT}
    restart: always
    privileged: true

    network_mode: host  # mac os 会失效  ports:  去掉！！！
    #    ports:
    #      - "${SERVICE_PORT}:${SERVICE_PORT}"
    command:
      - --bind 127.0.0.1
      - --port 6379
#      - --requirepass
      - --dir /data
      - --maxmemory 2G
      - --maxclients 50000
      # 多线程数量 = CPU核心数
      - --io-threads 2
      # 开启读多线程
      - --io-threads-do-reads yes
    volumes:
      - ./data-${SERVICE_PORT}:/data
      - ./custom-hosts:/etc/hosts:ro  # 只读挂载
