
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-${SERVICE_PORT} # 指定服务名

    #数据库和Redis 网络模式尽量不用桥接模式，使用host模式,以免损失性能
    network_mode: host

    command:
      --default-authentication-plugin=mysql_native_password
     
      #表名不区分大小写
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --explicit_defaults_for_timestamp=true
      --collation-server=utf8mb4_unicode_ci
      
      #数据库最大连接数
      --max_connections=1500
      
      #数据库端口
      --port=${SERVICE_PORT}
      
      #默认监听所有IP
      --bind-address=0.0.0.0

    volumes:
      - ./custom-hosts:/etc/hosts:ro  # 只读挂载
      - ./mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./mysql/logs:/var/log/mysql
      - ./mysql/mysql-files:/var/lib/mysql-files
      - ./mysql/data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    privileged: true
    restart: always
