listen_addresses = '*'
port = 5432
max_connections = 1000
shared_buffers = 256MB

wal_level = replica
max_wal_size = 1GB
min_wal_size = 80MB

logging_collector = on
log_destination = 'stderr'
log_directory = '/var/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_min_duration_statement = 3000

password_encryption = scram-sha-256
timezone = 'Asia/Shanghai'
client_encoding = 'UTF8'
