version: '3.8'

networks:
  nacos_net:
    driver: bridge

services:
  nacos:
    env_file:
      - ../cluster.env

    image: nacos/nacos-server:v2.5.1

    container_name: nacos-${SERVICE_HOSTNAME}-${SERVICE_PORT}

    hostname: ${SERVICE_HOSTNAME}  # 显式设置主机名

    networks:
      - nacos_net

    restart: always
    privileged: true

    volumes:
      - ../custom-hosts:/etc/hosts:ro  # 只读挂载
      - ./nacos/data:/home/nacos/data
      - ./nacos/conf:/home/nacos/conf
      - ./nacos/logs:/home/nacos/logs

    ports:
      - "${SERVICE_PORT}:8848"  # 映射到宿主机不同端口
