#Auto gen by simple-dao-codegen ${.now}

spring:
  application:
    name: entity-server

  #线程池配置
  task:
    execution:
      pool:
        core-size: 200

    scheduling:
      pool:
        size: 30

  #环境配置
  profiles:
    active: local # 本地环境
#    active: @spring.profiles.active@

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid: #单独使用druid时的配置
      initial-size: 50
      max-active: 500
      min-idle: 50
      max-wait: 60000
      min-evictable-idle-time-millis: 1800000
      max-evictable-idle-time-millis: 1800000
      time-between-eviction-runs-millis: 0
      validation-query: select 1
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filters: stat,wall
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
        enabled: true
        url-pattern: /druid/*
        allow: " "


    #    url: jdbc:h2:./dev.db;MODE=MySQL;
    url: jdbc:h2:mem:dev.db;
    username: dev
    password: dev

  jpa:
    show-sql: false
    generate-ddl: true
    database: H2
    #关闭视图事务，避免jpa 出现 N + 1 查询
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        #模块表名前缀映射类，重要
        physical-strategy: com.levin.commons.dao.support.EntityNamingStrategy

  #      MYSQL 配置选项
  #      properties:
  #        hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
  #        hibernate.id.new_generator_mappings: false

  #        hibernate.dialect.storage_engine: innodb


#日志配置
logging:
  level:
    root: info
    com.levin: trace

#swagger配置
swagger:
  enabled: true
#  enable: @swagger.enable@
