<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.levin.commons</groupId>
    <version>${revision}</version>
    <artifactId>simple-dao-codegen-example</artifactId>

    <!--  代码生成插件  请把以下配置加入到项目的根 pom.xml 文件中    -->

    <properties>

        <revision>4.2.0-SNAPSHOT</revision>

        <!-- Spring Boot 版本，请根据需要修改 -->
        <spring-boot.version>4.0.5</spring-boot.version>

        <levin.simple-dao.groupId>com.levin.commons</levin.simple-dao.groupId>
        <levin.simple-dao.version>4.2.0-SNAPSHOT</levin.simple-dao.version>

        <levin.service-support.groupId>com.levin.commons</levin.service-support.groupId>
        <levin.service-support.version>2.0.0-SNAPSHOT</levin.service-support.version>

    </properties>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://www.jitpack.io</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <!--  插件库 -->
            <id>jitpack.io</id>
            <url>https://www.jitpack.io</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <plugins>

            <plugin>
                <groupId>${levin.simple-dao.groupId}</groupId>
                <artifactId>simple-dao-codegen</artifactId>
                <version>${levin.simple-dao.version}</version>
                <configuration>
                    <!-- 生成的控制器代码是否包括目录-->
                    <isCreateControllerSubDir>true</isCreateControllerSubDir>

                    <!-- 是否生成BizController -->
                    <isCreateBizController>true</isCreateBizController>

                    <!-- 生成的DTO的Schema注解中描述的配置是否使用类引用-->
                    <isSchemaDescUseConstRef>true</isSchemaDescUseConstRef>

                    <!-- 集成 OakBaseFramework -->
                    <enableOakBaseFramework>false</enableOakBaseFramework>

                    <!-- 集成 DubboFramework -->
                    <enableDubbo>false</enableDubbo>

                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>${levin.service-support.groupId}</groupId>
                        <artifactId>service-support</artifactId>
                        <version>${levin.service-support.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

        </plugins>
    </build>

</project>
